os: Visual Studio 2017
environment:
  GCP_PASSWD:
    secure: /kPjA5Ff2c6ZDhU7y6TiUWiR4Jr4uXyLKWan35EXXTI=
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc

branches:
  only:
    - master

install:
  # Install janus.
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  - gitversion.exe > packages/desktop/gitversion.json
  - ps: $env:VERSION_BASE = "v$(gitversion.exe /showvariable Major).$(gitversion.exe /showvariable Minor).x"
    # expected by Electron Builder config
  - ps: $env:APP_VERSION_GIT_TAG="$(gitversion.exe /showvariable FullSemVer)-$(gitversion.exe /showvariable ShortSha)"
  - echo %VERSION_BASE% %APP_VERSION_GIT_TAG%

  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup update
  - rustc -vV
  - cargo -vV
  - rustup component add rust-src
  - for /f %%i in ('rustc --print sysroot') do set RUST_SRC_PATH=%%i\lib\rustlib\src\rust\src
  - cmd: set RUST_BACKTRACE=1
  - cmd: set RUSTFLAGS=-C target-feature=+crt-static

cache:
 - '%USERPROFILE%\.cargo'

build_script:
  - cargo build --all --release
  - 7z a emerald-bin-win-%VERSION_GIT_TAG%.zip ./target/release/*.exe

artifacts:
    - path: '*.zip'
      name: emerald-bin

#test_script:
#  - cargo test --all --release %cargoflags%

deploy_script:
    - openssl aes-256-cbc -d -in gcloud-appveyor.json.enc -k %GCP_PASSWD% -out gcloud-appveyor.json -md sha256
    - ps: >-
          If ($env:APPVEYOR_REPO_BRANCH -eq 'ci') {
            janus.exe deploy -to="builds.etcdevteam.com/emerald-cli/$env:VERSION_BASE/" -files="./*.zip" -key="./gcloud-appveyor.json"
          }
    - rm gcloud-appveyor.json
