language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - binutils-dev

notifications:
  email:
    on_success: never
before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi
- travis_wait cargo install rustfmt --force || true

before_script:
- export PATH="$PATH":~/.cargo/bin
- echo "\$ rustfmt --version"
- cargo fmt --all -- --version -f

script:
- export RUST_BACKTRACE=1
- cargo fmt --all -- --verbose --write-mode=diff -f
- cargo test --all --verbose
- cargo build --all --verbose --release

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --exclude-pattern=/.cargo --verify target/cov target/debug/emerald_rs-* &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qXqFCva/yJfwdJzLUazv3AUqvnbUWWEvCOoZHMkByK7/OP1yGdB/q7R24IRAf5SvfEk9TR8a81i+tiy/3iLfgrrBPLc077cLB4q6q1O1yBIrRTg61ggUDyiKaZDZqHtuvI2ocTnFM5jXTuEXVVGt0HA1IO3ezogmcVi9UrQp5rDDCWqPcNviTVweTICLb9PAWKmhbGrGmR3BVuNjmBCDJr25qnW6wors93xfCrpePepnl92gvPrp30WmQ2E+bgV+Hoeu9gJjCIjRU8bTmDWEdkBa3Qe8xIMU+SAw7CBUWRALh5q1HX0M7RYpg3zOEdVdWZ+OwDTO0mc40UdaV5rkx029ird4mC96bkHHemYITJJrDrwjoni9wSbnhZaNefZeKf8pAGLUO/+NwtcYbj8ogYdnsweAMRiZUvA15/tzk6kMQqBILjL605YayPWt9XvdU06gLjWtEd8qlOqt+xBPat3dKw15Xkb8XPM8bc6+YBHDvJC9tF4vozOsj9Sh4b/RV9+tB0xrjniY/ZRMtGe6JJO+7+7naszekz+F9lZJocmAhbX7XUsgyvjhmVn/1+IKnJQ/iqIn7FNQa+7y9ONmQxke4aibKdM3vTicgwwPD4IY2i9MGLCBDUFIiu70k8pJ2Gy4xa8E0LupcHui4uysG2ukqJhPU/4rN9v7HZznE3Y=
  file: target/release/emerald
  on:
    repo: ethereumproject/emerald-rs
    branch: master
    tags: true
