language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
notifications:
  email:
    on_success: never
before_install:
- travis_wait cargo install rustfmt --force || true
before_script:
- export PATH="$PATH":~/.cargo/bin
- echo "\$ rustfmt --version"
- cargo fmt --all -- --version
script:
- export RUST_BACKTRACE=1
- cargo fmt --all -- --verbose --write-mode=diff
- cargo test --all --verbose
- cargo build --all --verbose --release