language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
    env: ARCH=x86_64 TARGET=x86_64-unknown-linux-gnu
  - linux
    env: ARCH=i686 TARGET=i686-unknown-linux-gnu
  - osx
    env: ARCH=x86_64 TARGET=x86_64-apple-darwin
  - osx
    env: ARCH=i686 TARGET=i686-apple-darwin
before_script:
  - |
    (travis_wait cargo install rustfmt --force || true)
script:
  - |
    export RUST_BACKTRACE=1 &&
    export PATH="$PATH":~/.cargo/bin &&
    echo "\$ cargo --version --verbose" &&
    cargo --version --verbose &&
    echo "\$ rustc --version --verbose" &&
    rustc --version --verbose &&
    echo "\$ rustfmt --version" &&
    cargo fmt -- --version &&
    cargo fmt -- --verbose --write-mode=diff &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose --release) &&
    (test "$TRAVIS_RUST_VERSION" != nightly || cargo build --verbose --features "dev") &&
    cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
