language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=i686-unknown-linux-gnu
  - TARGET=i686-apple-darwin
  - TARGET=x86_64-apple-darwin
matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      os: osx
    - env: TARGET=i686-apple-darwin
      os: linux
    - env: TARGET=x86_64-apple-darwin
      os: linux
before_script:
  - |
    export RUST_BACKTRACE=1 &&
    export PATH="$PATH":~/.cargo/bin &&
    (travis_wait cargo install rustfmt --force || true) &&
    echo "\$ cargo --version --verbose" &&
    cargo --version --verbose &&
    echo "\$ rustc --version --verbose" &&
    rustc --version --verbose &&
    echo "\$ rustfmt --version" &&
    cargo fmt -- --version
script:
  - |
    cargo fmt -- --verbose --write-mode=diff &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose --release) &&
    (test "$TRAVIS_RUST_VERSION" != nightly || cargo build --verbose --features "dev") &&
    cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
