language: rust
cache: cargo
matrix:
  include:
    # Stable
    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
      os: linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
      os: linux
    - env: TARGET=i686-apple-darwin
      rust: stable
      os: osx
    - env: TARGET=x86_64-apple-darwin
      rust: stable
      os: osx
    # Beta
    - env: TARGET=i686-unknown-linux-gnu
      rust: beta
      os: linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
      os: linux
    - env: TARGET=i686-apple-darwin
      rust: beta
      os: osx
    - env: TARGET=x86_64-apple-darwin
      rust: beta
      os: osx
    # Nightly
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
      os: linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      os: linux
    - env: TARGET=i686-apple-darwin
      rust: nightly
      os: osx
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
before_script:
  - |
    (travis_wait cargo install rustfmt --force || true) &&
    export RUST_BACKTRACE=1 &&
    export PATH="$PATH":~/.cargo/bin &&
    echo "\$ cargo --version --verbose" &&
    cargo --version --verbose &&
    echo "\$ rustc --version --verbose" &&
    rustc --version --verbose &&
    echo "\$ rustfmt --version" &&
    cargo fmt -- --version
script:
  - |
    cargo fmt -- --verbose --write-mode=diff &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose --release) &&
    (test "$TRAVIS_RUST_VERSION" != nightly || cargo build --verbose --features "dev") &&
    cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
