dist: trusty
sudo: required
language: rust
cache: cargo
rust: stable
env:
  global:
    - TARGET=x86_64-unknown-linux-gnu
matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu BUILD_OPENSSL_VERSION=1.0.1u
      addons:
        apt:
          packages:
            - gcc-multilib
            - libssl-dev
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: osx
      env: TARGET=i686-apple-darwin
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
before_install:
  - rustup target add $TARGET || true
  - travis_wait cargo install rustfmt --force || true
  - ./build.sh
before_script:
  - export PATH="$PATH":~/.cargo/bin
  - echo "\$ rustfmt --version"
  - cargo fmt -- --version
script:
  - export RUST_BACKTRACE=1
  - cargo fmt -- --verbose --write-mode=diff
  - test "$TRAVIS_RUST_VERSION" == nightly || cargo test --target=$TARGET --verbose
  - test "$TRAVIS_RUST_VERSION" != nightly || cargo test --target=$TARGET --verbose --features "dev"
  - cargo build --target=$TARGET --verbose --release
  - cargo doc --no-deps
