[package]
name = "emerald"
version = "0.0.1"
authors = ["Dmitry Ulanov <dulanov@gmail.com>"]
description = "Ethereum classic web3 like connector written in Rust"
homepage = "http://etcdevteam.com"
repository = "https://github.com/ethereumproject/emerald-rs"
documentation = "https://docs.rs/emerald-rs"
keywords = ["rust", "bootstrap", "ethereum-classsic", "blockchain", "crypto-wallet", "web3"]
categories = ["ethereum-classic"]
readme = "README.adoc"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "ethereumproject/emerald-rs" }
appveyor = { repository = "ethereumproject/emerald-rs" }

[lib]
name = "emerald"
path = "src/lib.rs"

[[bin]]
name = "emerald-cli"
path = "src/main.rs"

[dependencies]
futures = "0.1"
jsonrpc-core = { git = "https://github.com/ethcore/jsonrpc.git", branch="master" }
jsonrpc-minihttp-server = { git = "https://github.com/ethcore/jsonrpc.git", branch="master" }
lazy_static = "0.2"
log = "0.3"
regex = "0.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
# optional dependencies
docopt = { version = "0.7", optional = true }
env_logger = { version = "0.4", optional = true }
hyper = { version = "0.10", optional = true }
reqwest = { version = "0.4", optional = true }
rustc-serialize = { version = "0.3", optional = true }
clippy = {version = "0.0", optional = true}
eth-secp256k1 = { git = "https://github.com/ethcore/rust-secp256k1" }
tiny-keccak = "1.2"
byteorder = "1.0"

[dev-dependencies]

[features]
default = ["cli", "http"]
cli = ["docopt", "env_logger", "rustc-serialize"]
http = ["hyper", "reqwest"]
dev = ["clippy"]
